name: speedtest-ng
base: core26
version: '0.8.4'
summary: A command-line tool for testing internet speed using Speedtest.net
description: |
  A command-line tool for testing internet speed using Speedtest.net, written in Crystal.
  Inspired by the Python-based speedtest-cli.
contact: anton.maminov@gmail.com

grade: stable
confinement: strict

type: app
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
compression: lzo

license: MIT

website: https://github.com/mamantoha/speedtest-ng
issues: https://github.com/mamantoha/speedtest-ng/issues
source-code: https://github.com/mamantoha/speedtest-ng.git

apps:
  speedtest-ng:
    command: bin/speedtest-ng
    plugs:
      - network

parts:
  speedtest-ng:
    plugin: nil
    source: ./
    build-snaps:
      - crystal/latest/stable
    build-packages:
      - git
      - libevent-dev
      - libgc-dev
      - libpcre2-dev
      - libssl-dev
      - libxml2-dev
      - libyaml-dev
      - pkg-config
      - zlib1g-dev
    stage-packages:
      - libevent-2.1-7
      - libgc1
      - libpcre2-8-0
      - libssl3
      - libxml2
      - libyaml-0-2
      - zlib1g
    override-build: |
      shards install --production --skip-postinstall
      shards build --release -- -Dpreview_mt -Dexecution_context --skip-postinstall
      install -Dm755 bin/speedtest-ng "$CRAFT_PART_INSTALL/bin/speedtest-ng"
